export const IS_PC = "IS_PC"
export const LOGIN = "LOGIN"
export const SIGNOFF = "SIGNOFF"
export const SAVE_SUBSCRIPTION = "SAVE_SUBSCRIPTION"
export const OPEN_MENU_MAIN_MOVIL = "OPEN_MENU_MAIN_MOVIL"
